version: "3.9"

services:
  api:
    build: .
    container_name: coconut-api
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mysql:8.0.36
    container_name: coconut-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: coconut_event_hub
    ports:
      - "3307:3306"
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: